version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - koppen
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: rspec-rails
    versions:
    - 5.0.0
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2.1
  - dependency-name: bootsnap
    versions:
    - 1.6.0
  - dependency-name: rubocop
    versions:
    - 1.9.0
  - dependency-name: capybara
    versions:
    - 3.35.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - koppen
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.6
    - 1.4.0
    - 1.4.1
  - dependency-name: webpack
    versions:
    - 5.30.0
    - 5.31.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@rails/webpacker"
    versions:
    - 6.0.0-beta.6
  - dependency-name: css-minimizer-webpack-plugin
    versions:
    - 1.3.0
  - dependency-name: tailwindcss
    versions:
    - 2.0.4
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.10
    - 7.13.12
    - 7.13.9
  - dependency-name: css-loader
    versions:
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: sass-loader
    versions:
    - 11.0.1
  - dependency-name: sass
    versions:
    - 1.32.5
