# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.6.5-node
         environment:
         - PG_HOST=localhost
         - PG_USER=ubuntu

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
       - image: circleci/postgres:11.5
         environment:
         - POSTGRES_USER=ubuntu
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - add_ssh_keys:
          fingerprints:
            - "9c:b5:2f:d3:6a:e1:c8:1d:cb:dd:47:b9:a2:63:97:ed"

      - run:
          name: install dependencies
          command: |
            gem install bundler
            bundle update --bundler
            bundle install --jobs=4 --retry=3 --path="./vendor/bundle"
            bundle clean --force
            bin/yarn

      - save_cache:
          paths:
            - ./node_modules
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}

      # Database setup
      - run:
          name: setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate
            bundle exec rails db:environment:set RAILS_ENV=test
          environment:
            DATABASE_URL: "postgres://ubuntu:@localhost:5432/circle_test"

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            bundle exec rake
          environment:
            DATABASE_URL: "postgres://ubuntu:@localhost:5432/circle_test"

      - run:
          name: Precompile assets
          command: |
            bundle exec rake assets:precompile
          environment:
            DATABASE_URL: "postgres://ubuntu:@localhost:5432/circle_test"

      - run:
          name: Lint code
          command: |
            bundle exec rubocop
          environment:
            DATABASE_URL: "postgres://ubuntu:@localhost:5432/circle_test"

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
